# This file contains the outputs that are generated by the Terraform configuration files.
# These outputs can be used by other Terraform configurations or scripts.

output "instance1_public_ip" {
  value = aws_instance.sample1.public_ip
}

output "instance2_public_ip" {
  value = aws_instance.sample2.public_ip
}

output "db_instance_addr" {
  value = aws_db_instance.sample_db.address
  
}